Models/Entities/Module.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LMSGrupp3.Models.Entities
{
    public class Module
    {
        [Key]
        [Required]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Module Description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "{0} must be specified")]
        [Display(Name = "Startdate")]
        [DataType(DataType.Date)]
        public DateTime StartTime { get; set; }

        [Required(ErrorMessage = "{0} must be specified")]
        [Display(Name = "End date")]
        [DataType(DataType.Date)]
        public DateTime EndTime { get; set; }

        [Display(Name = "Activity")]
        public ICollection<ActivityModel> ActivityModels { get; set; }

        public ICollection<Document> Documents { get; set; }
        // Navigational reference 
        [ForeignKey("CourseId")]
        public int CourseId { get; set; }

        public Course Course { get; set; }
    }
}

Controllers/ActivityModelsController.cs
using LMSGrupp3.Data;
using LMSGrupp3.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace LMSGrupp3
{
    public class ActivityModelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ActivityModelsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ActivityModels
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ActivityModel.Include(a => a.ActivityType);




            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ActivityModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activityModel = await _context.ActivityModel
                .Include(a => a.ActivityType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (activityModel == null)
            {
                return NotFound();
            }

            return View(activityModel);
        }

        // GET: ActivityModels/Create
        public IActionResult Create()
        {
            ViewData["ActivityTypeId"] = new SelectList(_context.Set<ActivityType>(), "Id", "Name");

            var @activityModel = new ActivityModel
            {
                ModuleId = int.Parse(TempData.Peek("LastModuleId").ToString()),
                StartDate = DateTime.Parse(TempData.Peek("LastModuleStartDate").ToString().Replace("00:00:00", "09:00:00")),
                StopDate = DateTime.Parse(TempData.Peek("LastModuleStartDate").ToString().Replace("00:00:00", "12:15:00"))
            };


            if (activityModel.ModuleId > 0)
            {
                var module = _context.Module.Where(m => m.Id == activityModel.ModuleId).SingleOrDefault();
                if (module != null)
                {
                    var startTime = module.StartTime;  //.ToString("yyyy-dd-MM hh:mm");
                    var endTime = module.StartTime;  //.ToString("yyyy-dd-MM hh:mm");

                                  

               
                    ViewData["modTimeStart"] = module.StartTime.ToString("dd/MM hh:mm");
                    ViewData["modTimeEnd"] = module.EndTime.ToString("dd/MM hh:mm");
                
                    ViewData["startTime"] = startTime.ToString("yyyy-dd-MM hh:mm");
                    ViewData["endTime"] = endTime.ToString("yyyy-dd-MM hh:mm");

                }

            }


            return View(@activityModel);
        }

        // POST: ActivityModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ActivityTypeId,Name,StartDate,StopDate,Description,ModuleId")] ActivityModel activityModel)
        {
            Boolean timeError = false;

            ViewData["errorTimeStart"] = "";
            ViewData["errorTimeEnd"] = "";

            if (ModelState.IsValid)
            {
                var module = _context.Module.Where(m => m.Id == activityModel.ModuleId).SingleOrDefault();
                if (module != null)
                {
                    if (activityModel.StartDate < module.StartTime)  // Före modulen
                    {
                        timeError = true;
                        ViewData["errorTimeStart"] = "Starttid kan inte vara före modulens starttid!";
                    }
                    else if (activityModel.StartDate > module.EndTime)  // Efter modulen
                    {
                        timeError = true;
                        ViewData["errorTimeStart"] = "Starttid kan inte vara efter modulens sluttid!";
                    }

                    if (activityModel.StopDate > module.EndTime)  // Efter modulen
                    {
                        timeError = true;
                        ViewData["errorTimeEnd"] = "Sluttid kan inte vara efter modulens sluttid!";
                    }
                    else if (activityModel.StopDate < activityModel.StartDate)  // Före starttid
                    {
                        timeError = true;
                        ViewData["errorTimeEnd"] = "Sluttid kan inte vara före starttid!";
                    }


                    if (timeError == false)
                    {
                        _context.Add(activityModel);
                        await _context.SaveChangesAsync();

                        var url = "~/Modules/Details/" + activityModel.ModuleId;
                        return LocalRedirect(url);
                        //                return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        var startTime = module.StartTime;
                        var endTime = module.StartTime;

                        // För att få t.ex: 24/12 12:30
                        CultureInfo culture = CultureInfo.CreateSpecificCulture("sv-SE");  // en-US
                        CultureInfo ci = CultureInfo.InvariantCulture;

                        // 24/12 12:30
                        ViewData["modTimeStart"] = module.StartTime.ToString("dd/MM hh:mm", ci);
                        ViewData["modTimeEnd"] = module.EndTime.ToString("dd/MM hh:mm", ci);
                        // 1999-12-24 12:30
                        ViewData["startTime"] = startTime.ToString("yyyy-dd-MM hh:mm");
                        ViewData["endTime"] = endTime.ToString("yyyy-dd-MM hh:mm");
                    }
                }
            }




            ViewData["ActivityTypeId"] = new SelectList(_context.Set<ActivityType>(), "Id", "Name", activityModel.ActivityTypeId);
            return View(activityModel);
        }

        // GET: ActivityModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activityModel = await _context.ActivityModel.FindAsync(id);
            if (activityModel == null)
            {
                return NotFound();
            }
            ViewData["ActivityTypeId"] = new SelectList(_context.Set<ActivityType>(), "Id", "Name", activityModel.ActivityTypeId);
            return View(activityModel);
        }

        // POST: ActivityModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ActivityTypeId,Name,StartDate,StopDate,Description,ModuleId")] ActivityModel activityModel)
        {
            if (id != activityModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activityModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivityModelExists(activityModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //                return RedirectToAction(nameof(Index));
                var url = "~/Modules/Details/" + TempData.Peek("LastModuleId");
                return LocalRedirect(url);

            }
            ViewData["ActivityTypeId"] = new SelectList(_context.Set<ActivityType>(), "Id", "Name", activityModel.ActivityTypeId);
            return View(activityModel);
        }

        // GET: ActivityModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activityModel = await _context.ActivityModel
                .Include(a => a.ActivityType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (activityModel == null)
            {
                return NotFound();
            }

            return View(activityModel);
        }

        // POST: ActivityModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activityModel = await _context.ActivityModel.FindAsync(id);
            _context.ActivityModel.Remove(activityModel);
            await _context.SaveChangesAsync();
            //            return RedirectToAction(nameof(Index));
            var url = "~/Modules/Details/" + TempData.Peek("LastModuleId");
            return LocalRedirect(url);
        }

        private bool ActivityModelExists(int id)
        {
            return _context.ActivityModel.Any(e => e.Id == id);
        }
    }
}

Controllers/CoursesController.cs
using LMSGrupp3.Data;
using LMSGrupp3.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using LMSGrupp3.ViewModels.Teacher;


namespace LMSGrupp3.Controllers
{
    //[Authorize(Roles = "Teacher,Student")]
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public CoursesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Courses
        public async Task<IActionResult> CourseStudents()
        {
            User currentUser = await _userManager.GetUserAsync(HttpContext.User);
            UserCourse actCourse = _context.UserCourse.FirstOrDefault(c => c.UserId == currentUser.Id);
            Course classMates;

            classMates = await _context
                .Course
                .Include(aus => aus.Users)
                    .ThenInclude(au => au.User)
                .FirstOrDefaultAsync(c => c.Id == _context
                    .UserCourse
                    .FirstOrDefault(u => u.UserId == _userManager
                        .GetUserId(HttpContext.User)
                        .ToString())
                    .CourseId);

            if (classMates != null)
                ViewData["Rubrik"] = "Course Mates";
            else
                ViewData["Rubrik"] = "Not Currently assigned to Course";

            return View(classMates);
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _context
                .Course
                .Include(m => m.Modules)
                .ThenInclude(ma => ma.ModuleActivities)
                .ThenInclude(at => at.ActivityType)
                .Include(auc => auc.Users)
                .ThenInclude(au => au.User)
                .ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(m => m.Modules)
                .ThenInclude(ma => ma.ModuleActivities)
                .Include(au => au.Users)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Create(CreateCourseViewModel courseModel)
        {
            if (ModelState.IsValid)
            {
                var course = new Course
                {
                    Name = courseModel.Name,
                    Description = courseModel.Description,
                    StartDate = courseModel.StartDate
                };

                ViewBag.Result = "Course created successfully!";
                _context.Add(course);
                await _context.SaveChangesAsync();
               
            }
            return View();
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,StartDate")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ViewBag.Result = "Course edited successfully!";
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View();
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.Id == id);
        }
    }
}

Views/Modules/Create.cshtml
@using Microsoft.AspNetCore.Http
@model LMSGrupp3.Models.Entities.Module

@{
    ViewData["Title"] = "Create Module in Course: "+@TempData.Peek("LastCourseName");
}
<br />
<h1>Create Module in Course: @TempData.Peek("LastCourseName")</h1>
<p>Course Starts: @ViewData["courseTimeStart"]</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" autofocus />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
                <span class="text-danger">@ViewData["errorTimeStart"]</span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
                <span class="text-danger">@ViewData["errorTimeEnd"]</span>
            </div>
            <div>
                <input hidden asp-for="@Model.CourseId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Skapa modul" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>
<hr />
<div>
    <a class="btn btn-sm btn-info" asp-controller="Courses" asp-action="Details" asp-route-id="@TempData.Peek("LastCourseId")"><i class="fas fa-undo-alt"></i> Tillbaka till kursdetaljer för @TempData.Peek("LastCourseName")</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Modules/Details.cshtml
@model LMSGrupp3.Models.Entities.Module

@{
    ViewData["Title"] = "Module Info";
    TempData["LastModuleName"] = Model.Name;
    TempData["LastModuleId"] = Model.Id;
    TempData["LastModuleStartDate"] = Model.StartTime.ToString();
    TempData["LastModuleStopDate"] = Model.EndTime.ToString();

}

<h1>@TempData.Peek("LastCourseName") / @Html.DisplayFor(model => model.Name)</h1>

<div>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary btn-sm" asp-action="Edit" asp-route-id="@Model.Id"><i class="fas fa-pencil-alt"></i> Redigera modul @Html.DisplayFor(model => model.Name)</a>
    &nbsp;
    <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@Model.Id"><i class="far fa-trash-alt"></i> Radera modul  @Html.DisplayFor(model => model.Name)</a>
    <br />
    @if (Model.ModuleActivities.Count > 0)
    {
        <table class="table table-hover table-condensed">

            <thead>
                <tr>
                    <th>
                        Activity Type
                    </th>
                    <th>
                        Namn
                    </th>
                    <th>
                        Start Date
                    </th>
                    <th>
                        End Date
                    </th>
                    <th>
                        Description
                    </th>
                    @*<th></th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ModuleActivities)
                {
                    <tr onclick="window.location.href='../../ActivityModels/Details/@item.Id'">
                        <td title="Click to show details of activity @item.Name.">
                            @Html.DisplayFor(modelItem => item.ActivityType.Name)
                        </td>
                        <td title="Click to show details of activity @item.Name.">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td title="Click to show details of activity @item.Name.">
                            @Html.DisplayFor(modelItem => item.StartDate)
                        </td>
                        <td title="Click to show details of activity @item.Name.">
                            @Html.DisplayFor(modelItem => item.StopDate)
                        </td>
                        <td title="Click to show details of activity @item.Name.">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        @*<td>
                                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </td>*@
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <hr />
        <h5><i>Module @Model.Name currently has no activities!</i></h5>
    }
    <a class="btn btn-sm btn-primary" asp-controller="ActivityModels" asp-action="Create" asp-route-CourseId="@Model.Id"><i class="fas fa-plus"></i> Lägg till aktivitet</a>

    <hr />

    <a class="btn btn-sm btn-info" asp-controller="Courses" asp-action="Details" asp-route-id="@TempData.Peek("LastCourseId")"><i class="fas fa-undo-alt"></i> Tillbaka till kurs @TempData.Peek("LastCourseName")</a>
</div>

Views/Modules/Index.cshtml
@model IEnumerable<LMSGrupp3.Models.Entities.Module>

@{
    ViewData["Title"] = "Module";
}

<h1>Module</h1>

<p>
	<a class="btn btn-primary" asp-action="Create">Create New Module</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>