Controllers/CoursesController.cs
using LMSGrupp3.Data;
using LMSGrupp3.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using LMSGrupp3.ViewModels.Teacher;


namespace LMSGrupp3.Controllers
{
    //[Authorize(Roles = "Teacher,Student")]
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public CoursesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Courses
        public async Task<IActionResult> CourseStudents()
        {
            User currentUser = await _userManager.GetUserAsync(HttpContext.User);
            UserCourse actCourse = _context.UserCourse.FirstOrDefault(c => c.UserId == currentUser.Id);
            Course classMates;

            classMates = await _context
                .Course
                .Include(aus => aus.Users)
                    .ThenInclude(au => au.User)
                .FirstOrDefaultAsync(c => c.Id == _context
                    .UserCourse
                    .FirstOrDefault(u => u.UserId == _userManager
                        .GetUserId(HttpContext.User)
                        .ToString())
                    .CourseId);

            if (classMates != null)
                ViewData["Rubrik"] = "Course Mates";
            else
                ViewData["Rubrik"] = "Not Currently assigned to Course";

            return View(classMates);
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _context
                .Course
                .Include(m => m.Modules)
                .ThenInclude(ma => ma.ModuleActivities)
                .ThenInclude(at => at.ActivityType)
                .Include(auc => auc.Users)
                .ThenInclude(au => au.User)
                .ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(m => m.Modules)
                .ThenInclude(ma => ma.ModuleActivities)
                .Include(au => au.Users)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Create(CreateCourseViewModel courseModel)
        {
            if (ModelState.IsValid)
            {
                var course = new Course
                {
                    Name = courseModel.Name,
                    Description = courseModel.Description,
                    StartDate = courseModel.StartDate
                };

                ViewBag.Result = "Course created successfully!";
                _context.Add(course);
                await _context.SaveChangesAsync();
               
            }
            return View();
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,StartDate")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ViewBag.Result = "Course edited successfully!";
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View();
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.Id == id);
        }
    }
}

Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMSGrupp3.Data;
using LMSGrupp3.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using LMSGrupp3.Models.ViewModels.Student;
using LMSGrupp3.Models.ViewModels;
using LMSGrupp3.Extensions;
using LMSGrupp3.Models.ViewModels.Teacher;
using System.Data.Common;

namespace LMSGrupp3.Controllers
{
    public class ModulesController : Controller
    {
        private readonly ApplicationDbContext context;

        public ModulesController(ApplicationDbContext context)
        {
            this.context = context;
        }

        // GET: Modules
        public async Task<IActionResult> Index()
        {
            return View(await context.Modules.ToListAsync());
        }

        // GET: Modules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var module = await context.Modules
                .Include(c => c.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (module == null)
            {
                return NotFound();
            }

            // All activities in the module.
            var activities = await context.ModuleActivites.Where(a => a.ModuleId == module.Id).ToListAsync();

            // All activity Ids in the module.
            var activityIds = await context.Activities.Where(a => a.ModuleId == module.Id).Select(i => i.Id).ToListAsync();

            // All documents in the module.
            var documents = await context.Documents.Where(d => d.ModuleId == module.Id)
                .Include(a => a.Activity)
                .Include(u => u.AppUser)
                .ToListAsync();

            // All documents in the activities in the module.
            foreach (var doc in await context.Documents.Include(a => a.Activity).ToListAsync())
            {
                foreach (var i in activityIds)
                {
                    if (doc.ActivityId == i)
                    {
                        if (!documents.Contains(doc))
                        {
                            documents.Add(doc);
                        }

                    }
                }
            }

            var viewmodel = new ModuleDetailsViewModel
            {
                Module = module,
                Documents = documents
            };

            return View(viewmodel);
        }


        // GET: Modules/Create
        [HttpGet]
        public IActionResult Create(int courseId)
        {
            var @module = new Module
            {
                CourseId = courseId,
                StartTime = DateTime.Parse(TempData.Peek("LastCourseStartDate").ToString()),
                EndTime = DateTime.Parse(TempData.Peek("LastCourseStartDate").ToString())
            };

            ViewData["courseTimeStart"] = "";
            ViewData["startTime"] = "";

            if (module.CourseId > 0)
            {
                var course = context.Course.Where(c => c.Id == module.CourseId).SingleOrDefault();
                if (course != null)
                {
                   

                    ViewData["courseTimeStart"] = course.StartDate.ToString("dd/MM-yy", ci);
                    ViewData["startTime"] = course.StartDate.ToString("yyyy-dd-MM");
                }
            }

            return View(@module);
        }

        // POST: Modules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,StartTime,EndTime,CourseId")] Module @module)
        {
            Boolean timeError = false;

            ViewData["errorTimeStart"] = "";
            ViewData["errorTimeEnd"] = "";

            var course = context.Course.Where(m => m.Id == module.CourseId).SingleOrDefault();

            if (ModelState.IsValid)
            {
                if (course != null)
                {
                    if (module.StartTime < course.StartDate)  // Före kurs
                    {
                        timeError = true;
                        ViewData["errorTimeStart"] = "Start Time before course Start Time, not ok.!";
                    }

                    if (module.EndTime < module.StartTime)  // Före starttid
                    {
                        timeError = true;
                        ViewData["errorTimeEnd"] = "End Time before start time, not valid!";
                    }

                    if (timeError == false)
                    {
                        context.Add(@module);
                        await context.SaveChangesAsync();
                        var url = "~/Courses/Details/" + @module.CourseId;
                        return LocalRedirect(url);
                    }
                }
            }

            // Skapa data vid fel
            // CultureInfo culture = CultureInfo.CreateSpecificCulture("sv-SE");  // en-US
            

            ViewData["courseTimeStart"] = course.StartDate.ToString("dd/MM-yy", ci);
            ViewData["startTime"] = course.StartDate.ToString("yyyy-dd-MM");

            return View(@module);
        }

        // GET: Modules/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await context.Module.FindAsync(id);
            if (@module == null)
            {
                return NotFound();
            }
            return View(@module);
        }

        // POST: Modules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,StartTime,EndTime, CourseId")] Module @module)
        {
            if (id != @module.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(@module);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(@module.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                var url = "~/Courses/Details/" + @module.CourseId;
                return LocalRedirect(url);
                //                return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Modules/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await context.Module
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // POST: Modules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @module = await context.Module.FindAsync(id);
            context.Module.Remove(@module);
            await context.SaveChangesAsync();
            //            return RedirectToAction(nameof(Index));
            var url = "~/Courses/Details/" + TempData.Peek("LastCourseId");
            return LocalRedirect(url);
        }

        private bool ModuleExists(int id)
        {
            return context.Module.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using LMSGrupp3.Models.Entities
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject IEnumerable<Course> Course

<!DOCTYPE html>
<html>
    <link rel="stylesheet" href="~/css/site.css">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]BIG UNI - Learning Management System</title>
    <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
           </environment>
    <environment exclude="Development">
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
   @*<link rel="stylesheet" href="~/css/animate.css" />*@
    
    
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-secondary">
            @*        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">*@
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/biguni2.jpg" height="50" width="50"/>
                    <span id="header-tagline">The Best Learning Platform</span>
                </a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                   
                    <partial name="_LoginPartial" />
                     <ul class="navbar-nav flex-grow-1">
                         @if (User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Identity" asp-page="/Account/Create" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">Add+User </a>
                              </li> 
                               @* <li class="nav-item">
                                <a class="nav-link" asp-area="Identity" asp-page="/Account/Index" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">User </a>
                            </li>*@
                            
                                 <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                                  </li> 
                                    <li class="nav-item">  
                                    <a class="nav-link" asp-area="" asp-controller="Modules" asp-action="Index">Modules</a>
                                   </li> 
                                    <li class="nav-item"> 
                                    <a class="nav-link" asp-area="" asp-controller="ActivityModels" asp-action="Index">Activities</a>
                                   </li> 
                                    <li class="nav-item"> 
                                    <a class="nav-link" asp-area="" asp-controller="ActivityTypes" asp-action="Index">Activity-Types</a>
                                  </li> 
                                    <li class="nav-item"> 
                                    <a class="nav-link" asp-area="" asp-controller="Documents" asp-action="Index">Documents</a>
                                    </li> 
                               
                        }
                        else if (User.IsInRole("Student"))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Index">My Course</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Courses" asp-action="CourseStudents">Course Classlist</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                        }
                </div>
            </div>
        </nav>
    </header>
   <p></p> 
    
    <div class="container">
       
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

     
    <footer class="border-top footer text-center">
        
   @* <img src="~/images/elearn.png" height="40" width="40" class="fb-img/>*@
    
        @*<div class="container">
            &copy; 2022 - BIG UNI LMS - Created by Team Alex & Mattias*@
           
 
      @*-     <partial name="_CookieConsentPartial" />
            - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
      
       </div>
        
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>