Models/ViewModels/Student/ActivityListViewModel.cs
using LMSGrupp3.Models.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMSGrupp3.Models.ViewModels.Student
{
    public class ActivityListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [DisplayName("Start Time")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime StartTime { get; set; }
        [DisplayName("End Time")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime EndTime { get; set; }
        [DisplayName("Activity Type")]
        public string ActivityType { get; set; }
    }
}

Controllers/CoursesController.cs
using LMSGrupp3.Data;
using LMSGrupp3.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using LMSGrupp3.ViewModels.Teacher;


namespace LMSGrupp3.Controllers
{
    //[Authorize(Roles = "Teacher,Student")]
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public CoursesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Courses
        public async Task<IActionResult> CourseStudents()
        {
            User currentUser = await _userManager.GetUserAsync(HttpContext.User);
            UserCourse actCourse = _context.UserCourse.FirstOrDefault(c => c.UserId == currentUser.Id);
            Course classMates;

            classMates = await _context
                .Course
                .Include(aus => aus.Users)
                    .ThenInclude(au => au.User)
                .FirstOrDefaultAsync(c => c.Id == _context
                    .UserCourse
                    .FirstOrDefault(u => u.UserId == _userManager
                        .GetUserId(HttpContext.User)
                        .ToString())
                    .CourseId);

            if (classMates != null)
                ViewData["Rubrik"] = "Course Mates";
            else
                ViewData["Rubrik"] = "Not Currently assigned to Course";

            return View(classMates);
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _context
                .Course
                .Include(m => m.Modules)
                .ThenInclude(ma => ma.ModuleActivities)
                .ThenInclude(at => at.ActivityType)
                .Include(auc => auc.Users)
                .ThenInclude(au => au.User)
                .ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(m => m.Modules)
                .ThenInclude(ma => ma.ModuleActivities)
                .Include(au => au.Users)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Create(CreateCourseViewModel courseModel)
        {
            if (ModelState.IsValid)
            {
                var course = new Course
                {
                    Name = courseModel.Name,
                    Description = courseModel.Description,
                    StartDate = courseModel.StartDate
                };

                ViewBag.Result = "Course created successfully!";
                _context.Add(course);
                await _context.SaveChangesAsync();
               
            }
            return View();
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,StartDate")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ViewBag.Result = "Course edited successfully!";
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View();
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.Id == id);
        }
    }
}

Controllers/DocumentsController.cs
using LMSGrupp3.Data;
using LMSGrupp3.Models.Entities;
using LMSGrupp3.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Web;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace LMSGrupp3.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        private readonly IHostingEnvironment _hostingEnvironment;

        public DocumentsController(ApplicationDbContext context, IHostingEnvironment environment, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
            _hostingEnvironment = environment;
        }

        // GET: Documents
        public async Task<IActionResult> Index()
        {
            return View(await _context.Document.ToListAsync());
        }

        // GET: Documents/Create
        public async Task<IActionResult> Create()
        {
            DocumentFileViewModel doc = new DocumentFileViewModel();
            DateTime timestamp = DateTime.Now;
            doc.Timestamp = timestamp;

            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            doc.UserId = currentUser.Id.ToString();
            return View(doc);
        }

        //POST: Documents/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Timestamp,UserId,CourseId,ModuleId,ActivityId")] Document document)
        {
            
                if (ModelState.IsValid) {
                    _context.Add(document);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["ActivityId"] = new SelectList(_context.ActivityModel, "Id", "Id", document.ActivityId);
                ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", document.UserId);
                ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Id", document.CourseId);
                ViewData["ModuleId"] = new SelectList(_context.Module, "Id", "Id", document.ModuleId);
                return View(document);
            
        }

            [HttpPost]
        public async Task<IActionResult> UploadFile(List<IFormFile> files, DocumentFileViewModel dvm)
        {
            if (files == null)
            {
                return Content("file not selected");
            }

            var uploads = this._hostingEnvironment.WebRootPath;
            var filePath = this._hostingEnvironment.ContentRootPath;

            string path = Path.Combine(this._hostingEnvironment.WebRootPath, "files");
            if (!Directory.Exists(filePath))
            {
                Directory.CreateDirectory(filePath);
            }

            List<string> uploadedFiles = new List<string>();
            foreach (IFormFile file in files)
            {
                string fileName = Path.GetFileName(file.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    file.CopyTo(stream);
                    uploadedFiles.Add(fileName);
                }
            }

            if (ModelState.IsValid)
            {
                Document doc = new Document();
                DateTime timestamp = DateTime.Now;
                doc.Name = dvm.Name;
                doc.Description = dvm.Description;
                doc.UserId = dvm.UserId;
                doc.FileName = dvm.FileName;
                doc.Timestamp = dvm.Timestamp;
                doc.CourseId = dvm.CourseId;
                doc.ModuleId = dvm.ModuleId;
                doc.ActivityId = dvm.ActivityId;
                doc.Path = path;
                _context.Add(doc);
                
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult DownloadFile(int? id)
        {
            Document doc = _context.Document.Find(id);
            if(id == null)
            {
                return Content("File not found");
            }

            string path = doc.Path;
            byte[] fileBytes = System.IO.File.ReadAllBytes(path + "/" + doc.FileName);
            if (fileBytes == null)
            {
                return Content("File doesn't exist");
            }

            string fileName = doc.FileName;
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMSGrupp3.Data;
using LMSGrupp3.Models.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace LMSGrupp3.Controllers
{
    [Authorize(Roles = "Teacher,Student")]
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public StudentController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Student
        public async Task<IActionResult> Index()
        {
            UserCourse actCourse = null;
            Course course = null;
            var courseId = 0;

            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (currentUser != null)
            {
                actCourse = _context.UserCourse.FirstOrDefault(c => c.UserId == currentUser.Id);
            }

            if (actCourse != null)
            {
                courseId = actCourse.CourseId;
                course = await _context.Course
                    .Include(m => m.Modules)
                    .ThenInclude(ma => ma.ModuleActivities)
                    .ThenInclude(ma => ma.ActivityType)
                    .Include(au => au.Users)
                    .FirstOrDefaultAsync(m => m.Id == courseId);
                ViewData["Rubrik"] = course.Name;
            }
            else
            {
                ViewData["Rubrik"] = "Du verkar inte gå på någon kurs - kontakta din lärare eller skolan";
            }

            return View(course);
        }

        //GET: Student/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        //// GET: Student/Create
        public IActionResult Create()
        {
            return View();
        }

        //// POST: Student/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,StartDate")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        //// GET: Student/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        //// POST: Student/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,StartDate")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        //// GET: Student/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        //// POST: Student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.Id == id);
        }

    }
}

Views/Student/Index.cshtml
@model LMSGrupp3.Models.Entities.Course

@{
    ViewData["Title"] = "Student View";
    }

@{ if (Model != null)
    {
        <br />
        <h1>@ViewData["Rubrik"]</h1>

        <div>
            <dl class="row">
                <dd class="col-sm-2 font-weight-bold">
                    @Html.DisplayFor(model => model.StartDate)
                </dd>
                <dd class="col-sm-10 font-italic font-weight-light">
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>

        @*<div class="col-sm-12" style="margin-top:0; margin-bottom:20px; border-top:1px solid #bbbbbb; border-bottom:0; overflow:hidden;">
            <div class="col-sm-12" style="margin-top:0; margin-bottom:5px; margin-left:-15px; padding:0; padding-top:5px; font-size:0.85em;">
                <div class="col-sm-12"><b>Kursdokument</b></div>
                <div class="col-sm-3" style="display:inline;"><i class="far fa-file"></i> Kursdokument</div>
                <div class="col-sm-3" style="display:inline;"><i class="far fa-file"></i> Kursdokument 2</div>
                <div class="col-sm-3" style="display:inline;"><i class="far fa-file"></i> Kommentarer och bilder från föreläsningen</div>
                <div class="col-sm-3" style="display:inline;"><i class="far fa-file"></i> Kursdokument 4</div>
            </div>
        </div>*@

        <h4 class="row stuModules">Modules</h4>

        <div style="padding-bottom:30px;">
            @foreach (var item in Model.Modules)
            {
                <div class="row stuModuleRow">
                    @{

                        var moduleStart = item.StartTime.ToString("dd/MM");  // var moduleStart = String.Format("{0:d/M/yyyy HH:mm:ss}", item.StartTime);
                        var moduleEnd = item.EndTime.ToString("dd/MM");      // var moduleEnd = item.EndTime.ToString("yyddMM hh:mm", ci);
                        var moduleDescription = item.Description.ToString();
                        var moduleActivities = item.ModuleActivities;

                    }
                    @*<div class="col-md-9 col-sm-8">*@
                    <div class="card" style="margin:5px;">
                    <div class="card-block">
                    @*<a class="nav-link" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>*@
                    <h4><a asp-controller="ActivityModels" asp-action="Index" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample"
                       class="col-md-3 col-sm-4 stuModuleLink" style="" onclick="ToggleDocs(@item.Id);">
                        <i id="Ico-@item.Id" class="fa fa-plus stuModuleIcon"></i> @Html.DisplayFor(modelItem => item.Name)
                    </a>
                    </h4>
                    @*</div>*@

                    <a href="#activities-@item.Id" class="col-md-3 col-sm-4 text-left" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample" style="">
                    @moduleDescription
                    </a>

                    @*<div class="col-md-3 col-sm-4 col- text-right stuModuleDate">*@
                    <a href="#activities-@item.Id" class="col-md-3 col-sm-4 text-right stuModuleDate" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample" style="">
                        <br> Börjar: @moduleStart
                        <br> Slutar: @moduleEnd
                    </a>
                    </div>
                        <a asp-controller="Documents" asp-route-id="@item.Id" asp-action="Create">Upload Document</a>
                    </div>

                    <div id="Docs-@item.Id" class="col-sm-12" style="margin-top:5px; display:none;">
                        @*stuModuleDocHidden*@
                        <div style="font-style:italic"> @Html.DisplayFor(modelItem => item.Description)</div>
                        @*<div class="col-sm-12 stuModuleDocArea" style="margin-top:5px; padding-top:5px; margin-bottom:0; border-top:1px solid #bbbbbb; border-bottom:0; overflow:hidden;">
                            <div class="col-sm-12"><b>Dokument</b></div>
                            <div class="col-sm-3 stuModuleDocItem"><i class="far fa-file"></i> Schema</div>
                            <div class="col-sm-3 stuModuleDocItem"><i class="far fa-file"></i> Introduktion till modulen</div>
                            <div class="col-sm-3 stuModuleDocItem"><i class="far fa-file"></i> Moduldokument</div>
                            <div class="col-sm-3 stuModuleDocItem"><i class="far fa-file"></i> Kommentarer och bilder från föreläsningen</div>
                        </div>*@
                    </div>
                </div>

                <div id="activities-@item.Id" class="collapse">
                    @foreach (var activity in item.ModuleActivities.Where(a => a.ModuleId == item.Id))
                    {
                        // var timeStart = activity.StartDate.ToString("yyMMdd hh:mm"); /*yyyy - MM - dd hh: mm*/
                        //var timeEnd = activity.StopDate.ToString("yyMMdd hh:mm");

                        var timeStart = activity.StartDate.ToString("d/MM hh:mm");
                        var timeEnd = activity.StopDate.ToString("d/MM hh:mm");

                        <div class="row actRow">
                            <div class="col-sm-4 font-weight-bold">
                                @timeStart - @timeEnd
                            </div>
                            <div class="col-sm-6 font-weight-bold">
                                @activity.Name
                            </div>
                            <div class="col-sm-2 font-weight-bold">
                                @activity.ActivityType.Name
                            </div>
                            <div class="col-sm-9 font-italic">
                                @activity.ActivityType.Description
                            </div>
                            @*@if (@activity.ActivityType.Name == "Föreläsning")
                            {
                                <div class="col-sm-3 font-normal actInlamning">
                                    Lämna inlämningsuppgift
                                </div>
                            }*@

                            <hr />

                            <div class="col-sm-12" style="margin-top:0; margin-bottom:0; background:#fafafa; border-top:1px solid #bbbbbb; border-bottom:0; overflow:hidden;">
                                @*<div class="col-sm-12" style="margin-top:0; margin-bottom:5px; margin-left:-15px; padding:0; padding-top:5px; font-size:0.85em;">
                                    <div class="col-sm-12"><b>Aktivitetsdokument</b></div>
                                    <div class="col-sm-3" style="display:inline;"><i class="far fa-file"></i> Schema</div>
                                    <div class="col-sm-3" style="display:inline;"><i class="far fa-file"></i> Filmlista</div>
                                    <div class="col-sm-3" style="display:inline;"><i class="far fa-file"></i> Kommentarer och bilder från föreläsningen</div>
                                    <div class="col-sm-3" style="display:inline;"><i class="far fa-file"></i> Övningsuppgifter</div>
                                </div>*@
                            </div>
                        </div>
                    }
                </div>
            }

        </div>
    }
}

@{if (Model == null)
    {
        <br />
        <h3>@ViewData["Rubrik"]</h3>
    }
}